// import type { Metadata } from "next";
// import "@/styles/globals.css";
// import Link from "next/link";
// import { Button } from "@/components/ui/button";
// import { Facebook, Github, Instagram, Linkedin, PlusCircle } from "lucide-react";
// import { auth } from "@/lib/auth";
// import { Profile } from "@/components/ui/profile";
// import { headers } from "next/headers";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const session = await auth.api.getSession({
//     headers: headers(),
//   });

//   return (
//     <html lang="en">
//       <body>
//         <nav className="flex px-20 py-2 justify-between items-center bg-primary-foreground sticky inset-x-0 top-0 w-full">
//           <Link
//             className="font-bold text-4xl hover:-rotate-12 hover:scale-125 hover:-translate-y-1  hover:transition-all"
//             href="/"
//           >
//             N.
//           </Link>
//           <div className="space-x-10 font-medium text-xl/6 tracking-tight flex items-center">
//             <Link className="hover:underline hover:underline-offset-8" href="#">
//               Ngữ pháp
//             </Link>
//             <Link className="hover:underline hover:underline-offset-8" href="#">
//               Hán tự
//             </Link>
//             <Link className="hover:underline hover:underline-offset-8" href="#">
//               Diễn đàn
//             </Link>
//             {/* Profile */}
//             <Button asChild className="w-full sm:w-auto">
//               <Link href="/createBlog">
//                 <PlusCircle className="h-4 w-4" />
//               </Link>
//             </Button>
//             {session ? (
//               <Profile user={session?.user} />
//             ) : (
//               <Button asChild>
//                 <Link href="/login">Đăng nhập</Link>
//               </Button>
//             )}
//           </div>
//         </nav>
//         {children}
//         <footer className="bg-primary-foreground">
//           <div className="mx-auto flex h-[400px] items-center justify-center space-x-[400px]">
//             <div className="max-w-66">
//               <div className="items-center space-y-14 text-xl">
//                 <div className="font-medium">日本語らしい</div>
//                 <div className="space-y-5 font-medium">
//                   <div>Blogs</div>
//                   <div>Contact</div>
//                   <div>Quick Links</div>
//                 </div>
//               </div>
//             </div>
//             <div className="space-y-5">
//               <h1 className="text-xl font-medium">Social media</h1>
//               <div className="flex space-x-3">
//                 <Facebook />
//                 <Instagram />
//                 <Linkedin />
//                 <Link href="https://github.com/nguyenbaduy011/nihongo-rashii-revamp">
//                   <Github />
//                 </Link>
//               </div>
//             </div>
//           </div>
//         </footer>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import "@/styles/globals.css";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  Facebook,
  Github,
  Instagram,
  Linkedin,
  PlusCircle,
} from "lucide-react";
import { auth } from "@/lib/auth";
import { Profile } from "@/components/ui/profile";
import { headers } from "next/headers";
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
} from "@/components/ui/navigation-menu";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: headers(),
  });

  return (
    <html lang="en">
      <body>
        <main>
          <nav className="flex px-20 py-2 justify-between items-center bg-primary-foreground sticky inset-x-0 top-0 w-full z-10">
            <Link
              className="font-bold text-4xl hover:-rotate-12 hover:scale-125 hover:-translate-y-1  hover:transition-all"
              href="/"
            >
              N.
            </Link>
            <div className="space-x-10 font-medium text-xl/6 tracking-tight flex items-center">
              {/* <Link className="hover:underline hover:underline-offset-8" href="#">
              Ngữ pháp
            </Link> */}
              <NavigationMenu>
                <NavigationMenuList>
                  <NavigationMenuItem>
                    <NavigationMenuTrigger className="hover:text-black focus:bg-primary-foreground data-[active]:bg-primary-foreground/50 data-[state=open]:bg-bg-primary-foreground/50 text-xl/6 bg-primary-foreground hover:bg-primary-foreground transition-colors">
                      Ngữ pháp
                    </NavigationMenuTrigger>
                    <NavigationMenuContent>
                      <NavigationMenuLink>Link</NavigationMenuLink>
                    </NavigationMenuContent>
                  </NavigationMenuItem>
                </NavigationMenuList>
              </NavigationMenu>
              <Link
                className="hover:underline hover:underline-offset-8"
                href="#"
              >
                Hán tự
              </Link>
              <Link
                className="hover:underline hover:underline-offset-8"
                href="#"
              >
                Diễn đàn
              </Link>
              {/* Profile */}
              <Button asChild className="w-full sm:w-auto">
                <Link href="/blogs/createBlog">
                  <PlusCircle className="h-4 w-4" />
                </Link>
              </Button>
              {session ? (
                <Profile user={session?.user} />
              ) : (
                <Button asChild>
                  <Link href="/login">Đăng nhập</Link>
                </Button>
              )}
            </div>
          </nav>
          {children}
          <footer className="bg-primary-foreground">
            <div className="mx-auto flex h-[400px] items-center justify-center space-x-[400px]">
              <div className="max-w-66">
                <div className="items-center space-y-14 text-xl">
                  <div className="font-medium">日本語らしい</div>
                  <div className="space-y-5 font-medium">
                    <div>Blogs</div>
                    <div>Contact</div>
                    <div>Quick Links</div>
                  </div>
                </div>
              </div>
              <div className="space-y-5">
                <h1 className="text-xl font-medium">Social media</h1>
                <div className="flex space-x-3">
                  <Facebook />
                  <Instagram />
                  <Linkedin />
                  <Link href="https://github.com/nguyenbaduy011/nihongo-rashii-revamp">
                    <Github />
                  </Link>
                </div>
              </div>
            </div>
          </footer>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
