export const N5Grammars = [{
      id: "N5_1",
      romajiRead: "wa～desu",
      japaneseRead: "は～です",
      level: "N5",
      explain: `「です」 đặt ở cuối câu biểu thị thái độ lịch sự của người nói đối với người nghe. Khi dùng 「です」ở cuối câu, đối với tính từ đuôi な thì bỏ「な」 đi, còn đối với tính từ đuôi いthì để nguyên「い」`,
      meaning: "Thì...",
      usingWay: `N ✙ は ✙ な・いA ✙ です<br/>N1 ✙ は ✙ N2 ✙ です`,
    },
    {
      id: "N5_2",
      romajiRead: "～wa～dewa/jaarimasen",
      japaneseRead: "～は～では/じゃありません",
      level: "N5",
      explain: `Là dạng phủ định của「です」.「じゃありません」thường được sử dụng trong hội thoại hàng ngày, còn「ではありません」được sử dụng trong các bài phát biểu trang trọng hay trong văn viết.`,
      meaning: "N1 không phải là N2",
      usingWay: `N ✙ は ✙ な・いA ✙ では・じゃ ありません<br/>N1 ✙ は ✙ N2 ✙ では・じゃ ありません`,
    },
    {
      id: "N5_3",
      romajiRead: "wa～desuka",
      japaneseRead: "～は～ですか",
      level: "N5",
      explain: `「ですか」Được dùng khi người nói nêu rõ đối tượng cần xác nhận và dùng mẫu câu này để xác nhận. Trợ từ「か」mang chức năng xác nhận.`,
      meaning: "N1 là N2 phải không?",
      usingWay: `N ✙ は ✙ な・いA ✙ ですか<br/>N1 ✙ は ✙ N2 ✙ ですか`,
    },
    {
      id: "N5_4",
      romajiRead: "～no～",
      japaneseRead: "～の～",
      level: "N5",
      explain: `「の」Dùng để nối 2 danh từ lại với nhau, danh từ số 1 bổ nghĩa cho danh từ số 2. 『の』trong cấu trúc này, danh từ số 1 biểu thị nơi sở thuộc của danh từ số 2.`,
      meaning: "N2 thuộc N1",
      usingWay: `N1 ✙ の ✙ N2 ✙ です`,
    },
    {
      id: "N5_5",
      romajiRead: "～mo～",
      japaneseRead: "～も～",
      level: "N5",
      explain: `「も」Được dùng khi danh từ diễn tả chủ đề của câu giống với danh từ tương ứng ở câu trước.`,
      meaning: "N1 cũng là N2.",
      usingWay: `N1 ✙ も ✙ N2 ✙ です`,
    },
    {
      id: "N5_6",
      romajiRead: "～nansai desuka",
      japaneseRead: "～なんさい「何歳」ですか",
      level: "N5",
      explain: `Đây là mẫu câu được dùng để hỏi tuổi. <br/>Trong văn phong lịch sự, đối với người lớn tuổi: おいくつ được sử dụng để thay thế cho なんさい.`,
      meaning: "N thì bao nhiêu tuổi？",
      usingWay: `N ✙ は ✙ なんさい「何歳」✙ ですか<br/>おいくつ ✙ ですか`,
    },
    {
      id: "N5_7",
      romajiRead: "kore/sore/are",
      japaneseRead: "これ・それ・あれ",
      level: "N5",
      explain: `「これ」、「それ」、「あれ」 là các chỉ thị từ, được sử dụng như danh từ và không có danh từ đi liền sau chúng.<br/>「これ」 dùng để chỉ vật ở gần người nói, xa người nghe.<br/>「それ」 dùng để chỉ vật ở gần người nghe, xa người nói.<br/>「あれ」 dùng để chỉ vật ở xa cả hai người.`,
      meaning: "Cái này/ cái đó/ cái kia",
      usingWay: `これ・それ・あれ ✙ は ✙ N ✙ です`,
    },
    {
      id: "N5_8",
      romajiRead: "kono/sono/ano",
      japaneseRead: "この・その・あの",
      level: "N5",
      explain: `「この」、「その」、「あの」 là các chỉ thị từ bổ nghĩa cho danh từ.<br/>「この」dùng để chỉ người, vật ở gần người nói, xa người nghe.<br/>「その」dùng để chỉ người, vật ở gần người nghe, xa người nói.<br/>「 あの」dùng để chỉ người, vật ở xa cả người nói và người nghe.`,
      meaning: "...này/ ...đó/ ...kia",
      usingWay: `この・その・あの`,
    },
    {
      id: "N5_9",
      romajiRead: "...ka, ...ka",
      japaneseRead: "。。。か、。。。か",
      level: "N5",
      explain: `Mẫu câu nghi vấn này dùng để hỏi về sự lựa chọn của người nghe . Người nghe sẽ lựa chọn câu 1 hoặc câu 2.<br/>Đối với câu nghi vấn loại này , khi trả lời không dùng 「 はい」hay「 いいえ」 mà để nguyên câu lựa chọn .`,
      meaning: "N là～hay～là...",
      usingWay: `「文」✙ か、「文」✙ か`,
    },
    {
      id: "N5_10",
      romajiRead: "～no～",
      japaneseRead: "～の～",
      level: "N5",
      explain: `『の』Dùng để nối 2 danh từ lại với nhau, danh từ số 1 bổ nghĩa cho danh từ số 2.『の』trong cấu trúc này biểu thị tính sở hữu của chủ thể được nhắc đến.<br/>Khi một danh từ đã được nhắc đến trước đó trong câu hoặc đoạn văn, bạn có thể sử dụng の để thay thế danh từ đó, nhằm tránh việc lặp lại.`,
      meaning: "N2 của N1",
      usingWay: `N1 ✙ の ✙ N2`,
    },
    {
      id: "N5_11",
      romajiRead: "koko/soko/asoko・kochira/sochira/achira",
      japaneseRead: "ここ・そこ・あそこ／こちら・そちら・あちら",
      level: "N5",
      explain: `「ここ」、「そこ」、「あそこ」là các chỉ thị từ chỉ địa điểm.<br/>「ここ」dùng để chỉ địa điểm gần người nói, xa người nghe.<br/>「そこ」dùng để chỉ địa điểm gần người nghe, xa người nói.<br/>「あそこ」dùng để chỉ địa điểm xa cả người nói và người nghe.<br/>「こちら」、「そちら」、「あちら」là những đại từ chỉ phương hướng và cũng có thể dùng thay thế 「ここ」、「そこ」、「あそこ」để chỉ địa điểm trước mắt. Trường hợp này nó sẽ thể hiện sắc thái lịch sự hơn.`,
      meaning: "Chỗ này/ chỗ đó/ chỗ kia",
      usingWay: `ここ・そこ・あそこ ✙ は ✙ N(Danh từ chỉ địa điểm) ✙ です`,
    },
    {
      id: "N5_12",
      romajiRead: "～wa～desu",
      japaneseRead: "～は～です",
      level: "N5",
      explain: `Mẫu câu này được dùng để diễn đạt một vật, một người hay một địa điểm nào đó ở đâu.`,
      meaning: "N ở chỗ này/chỗ đó/chỗ kia.<br/> chỗ này/chỗ đó/chỗ kia là N. ",
      usingWay: `N ✙ は ✙ ここ・そこ・あそこ ✙ です<br/>N1 ✙ は ✙ N2 ✙ です`,
    },
    {
      id: "N5_13",
      romajiRead: "doko/dochira",
      japaneseRead: "どこ・どちら",
      level: "N5",
      explain: `「どこ」là nghi vấn từ hỏi về địa điểm, còn 「どちら」là nghi vấn từ hỏi về phương hướng. Tuy nhiên 「どちら」cũng có thể được dùng để hỏi về địa điểm và mang sắc thái lịch sự hơn「どこ」`,
      meaning: "Ở đâu/ Ở chỗ nào",
      usingWay: `N ✙ どこ・どちら ✙ ですか`,
    },
    {
      id: "N5_14",
      romajiRead: "～no～",
      japaneseRead: "～の～",
      level: "N5",
      explain: `Trường hợp N1 là tên quốc gia hoặc công ty còn N2 là tên của sản phẩm thì ngữ pháp này có nghĩa là N1 là sản phẩm của N2. Ở trường hợp này sử dụng nghi vấn từ「どこ」khi hỏi.`,
      meaning: "N2 của N1",
      usingWay: `N1 ✙ の ✙ N2`,
    },
    {
      id: "N5_15",
      romajiRead: "o～",
      japaneseRead: "お～",
      level: "N5",
      explain: `Tiền tố được thêm vào trước một từ có liên quan đến người nghe hoặc người ở ngôi thứ ba để bày tỏ sự kính trọng của người nói.`,
      meaning: "Tiền tố o",
      usingWay: `お ✙ N`,
    },
    {
      id: "N5_16",
      romajiRead: "～ikura～",
      japaneseRead: "～いくら～",
      level: "N5",
      explain: `「いくら」được sử dụng để hỏi giá của một thứ gì đó.`,
      meaning: "Bao nhiêu",
      usingWay: `N ✙ は ✙ いくら ✙ ですか`,
    },
    // {
    //   id: "N5_17",
    //   romajiRead: "",
    //   japaneseRead: "",
    //   level: "N5",
    //   explain: ``,
    //   meaning: "",
    //   usingWay: ``,
    // },
    // {
    //   id: "N5_18",
    //   romajiRead: "",
    //   japaneseRead: "",
    //   level: "N5",
    //   explain: ``,
    //   meaning: "",
    //   usingWay: ``,
    // },
    // {
    //   id: "N5_19",
    //   romajiRead: "",
    //   japaneseRead: "",
    //   level: "N5",
    //   explain: ``,
    //   meaning: "",
    //   usingWay: ``,
    // },
    // {
    //   id: "N5_20",
    //   romajiRead: "",
    //   japaneseRead: "",
    //   level: "N5",
    //   explain: ``,
    //   meaning: "",
    //   usingWay: ``,
    // },
    // {
    //   id: "N5_",
    //   romajiRead: "",
    //   japaneseRead: "",
    //   level: "N5",
    //   explain: ``,
    //   meaning: "",
    //   usingWay: ``,
    // },
    // {
    //   id: "N5_",
    //   romajiRead: "",
    //   japaneseRead: "",
    //   level: "N5",
    //   explain: ``,
    //   meaning: "",
    //   usingWay: ``,
    // },
    // {
    //   id: "N5_",
    //   romajiRead: "",
    //   japaneseRead: "",
    //   level: "N5",
    //   explain: ``,
    //   meaning: "",
    //   usingWay: ``,
    // },
    // {
    //   id: "N5_",
    //   romajiRead: "",
    //   japaneseRead: "",
    //   level: "N5",
    //   explain: ``,
    //   meaning: "",
    //   usingWay: ``,
    // },
    // {
    //   id: "N5_",
    //   romajiRead: "",
    //   japaneseRead: "",
    //   level: "N5",
    //   explain: ``,
    //   meaning: "",
    //   usingWay: ``,
    // },
    // {
    //   id: "N5_",
    //   romajiRead: "",
    //   japaneseRead: "",
    //   level: "N5",
    //   explain: ``,
    //   meaning: "",
    //   usingWay: ``,
    // },
    // {
    //   id: "N5_",
    //   romajiRead: "",
    //   japaneseRead: "",
    //   level: "N5",
    //   explain: ``,
    //   meaning: "",
    //   usingWay: ``,
    // },
    // {
    //   id: "N5_",
    //   romajiRead: "",
    //   japaneseRead: "",
    //   level: "N5",
    //   explain: ``,
    //   meaning: "",
    //   usingWay: ``,
    // },
    // {
    //   id: "N5_",
    //   romajiRead: "",
    //   japaneseRead: "",
    //   level: "N5",
    //   explain: ``,
    //   meaning: "",
    //   usingWay: ``,
    // },
    // {
    //   id: "N5_",
    //   romajiRead: "",
    //   japaneseRead: "",
    //   level: "N5",
    //   explain: ``,
    //   meaning: "",
    //   usingWay: ``,
    // },
    // {
    //   id: "N5_",
    //   romajiRead: "",
    //   japaneseRead: "",
    //   level: "N5",
    //   explain: ``,
    //   meaning: "",
    //   usingWay: ``,
    // },
    // {
    //   id: "N5_",
    //   romajiRead: "",
    //   japaneseRead: "",
    //   level: "N5",
    //   explain: ``,
    //   meaning: "",
    //   usingWay: ``,
    // },
    // {
    //   id: "N5_",
    //   romajiRead: "",
    //   japaneseRead: "",
    //   level: "N5",
    //   explain: ``,
    //   meaning: "",
    //   usingWay: ``,
    // },
    ]